---
- hosts: local

  vars:
    routers:
      - { name: s1-edge, asn: 64601, prefixes: ['10.0.0.0/24'] }
      - { name: s1-interco-1, asn: 64601 }
      - { name: s1-interco-2, asn: 64601 }
      - { name: s2-interco-1, asn: 64602 }
      - { name: s2-interco-2, asn: 64602 }
      - { name: s2-edge, asn: 64602, prefixes: ['192.168.0.0/24'] }

  tasks:

    - name: install the latest version of guaqqa ...
      package:
        name: quagga
        state: latest

    - name: enable ipv4 forwarding ...
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: copy default configuration files
      copy:
        src: "/usr/share/doc/quagga/examples/{{ item }}.conf.sample"
        dest: "/etc/quagga/{{ item }}.conf"
        owner: quagga
        group: quagga
        # We don't want to override config made on the file on router, only copy if file is not there
        force: no
      with_items:
        - "{{ daemon_list }}"
    
    - name: configure zebra daemon to start ...
      lineinfile:
        path: "/etc/quagga/daemons"
        regex: '^{{ item }}=no'
        line: "{{ item }}=yes"
      with_items:
        - "{{ daemon_list }}"

    - name: configure hostname in config files ...
      lineinfile:
        path: "/etc/quagga/{{ item }}.conf"
        regex: '^hostname'
        line: "hostname {{ item }}-{{ vm_hostname }}"
      with_items:
        - "{{ daemon_list }}"

    - name: configure vtysh in environment file ...
      lineinfile:
        path: "/etc/environment"
        line: "VTYSH_PAGER=more"

    # - name: configure router id in bgpd config file ...
    #   lineinfile:
    #     path: "/etc/quagga/bgpd.conf"
    #     regex: '^bgp router-id'
    #     line: "bgp router-id {{ ansible_eth0.ipv4.address }}"
    #   with_items:
    #     - "bgpd"
 
    # - name: configure router id in bgpd config file ...
    #   lineinfile:
    #     path: "/etc/quagga/bgpd.conf"
    #     regex: '^bgp router-id'
    #     line: "bgp router-id {{ ansible_eth0.ipv4.address }}"
    #   with_items:
    #     - "bgpd"

    - name: render quagga configuration files to /etc/quagga folder ...
      template:
        src: "{{ playbook_dir }}/{{ item }}.conf.j2"
        dest: /etc/quagga/{{ item }}.conf
      with_items:
        - "{{ daemon_list }}"
       
    - name: restart quagga service ...
      service:
        name: quagga
        state: restarted