---
- hosts: local

  tasks:

    - name: install the latest version of guaqqa ...
      package:
        name: quagga
        state: latest

    - name: enable ipv4 forwarding ...
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: copy default configuration files
      copy:
        src: "usr/share/doc/quagga/examples/{{ item }}.conf.sample"
        dest: "/etc/quagga/{{ item }}.conf"
        user: quagga
        group: quagga
      with_items:
        - 'zebra'
        - 'bgpd'
    
    - name: configure zebra daemon to start ...
      lineinfile:
        path: "/etc/quagga/daemons.conf"
        regex: '^{{ item }}=no'
        line: "{{ item }}=yes"
      with_items:
        - 'zebra'
        - 'bgpd'
