---
- hosts: local

  tasks:

    - name: install the latest version of guaqqa ...
      package:
        name: quagga
        state: latest

    - name: enable ipv4 forwarding ...
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes